# Generated by Django 2.2.9 on 2020-11-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=100, null=True, verbose_name='SEO название')),
                ('seo_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='SEO описание')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO ключевые слова')),
                ('og_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='OG заголовок')),
                ('og_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='OG описание')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='OG изображение')),
            ],
            options={
                'verbose_name': 'О нас(SEO)',
                'verbose_name_plural': 'О нас(SEO)',
            },
        ),
        migrations.CreateModel(
            name='FAQSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=100, null=True, verbose_name='SEO название')),
                ('seo_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='SEO описание')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO ключевые слова')),
                ('og_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='OG заголовок')),
                ('og_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='OG описание')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='OG изображение')),
            ],
            options={
                'verbose_name': 'Вопросы и ответы (SEO)',
                'verbose_name_plural': 'Вопросы и ответы (SEO)',
            },
        ),
        migrations.CreateModel(
            name='ProductSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=100, null=True, verbose_name='SEO название')),
                ('seo_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='SEO описание')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO ключевые слова')),
                ('og_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='OG заголовок')),
                ('og_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='OG описание')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='OG изображение')),
            ],
            options={
                'verbose_name': 'Товары (SEO)',
                'verbose_name_plural': 'Товары (SEO)',
            },
        ),
        migrations.CreateModel(
            name='ServiceSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=100, null=True, verbose_name='SEO название')),
                ('seo_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='SEO описание')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO ключевые слова')),
                ('og_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='OG заголовок')),
                ('og_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='OG описание')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='OG изображение')),
            ],
            options={
                'verbose_name': 'Услуги (SEO)',
                'verbose_name_plural': 'Услуги (SEO)',
            },
        ),
        migrations.CreateModel(
            name='SORTDSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=100, null=True, verbose_name='SEO название')),
                ('seo_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='SEO описание')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO ключевые слова')),
                ('og_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='OG заголовок')),
                ('og_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='OG описание')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='OG изображение')),
            ],
            options={
                'verbose_name': 'Главная страница(SEO)',
                'verbose_name_plural': 'Главная страница(SEO)',
            },
        ),
    ]
