# Generated by Django 2.2.9 on 2020-12-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название метрики')),
                ('code', models.TextField(verbose_name='Код метрики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('display_block_choice', models.CharField(choices=[('head', '<head>'), ('body', '<body>')], help_text='Выберите в каком html блоке показывать', max_length=10, verbose_name='В каком блоке показывать')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Аналитические метрики',
            },
        ),
    ]
